# Generated by Django 3.2.12 on 2023-05-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20230505_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Número de telefone deve ter 10 dígitos.', regex='^\\d{10}$')]),
        ),
    ]
